entries_men   = "607"
entries_women = "372"
entries_other = "22"
var weekday_distribution_m = [17.46, 14.66, 17.63, 16.80, 13.34, 8.73, 11.37]
var weekday_distribution_f = [14.52, 16.67, 17.47, 13.98, 15.32, 10.75, 11.29]
var weekday_chi = "0.591607734"
var table_overall_d_m = '<tr><td class="alignleft">German</td><td class="alignright">375</td></tr>\n<tr><td class="alignleft">English</td><td class="alignright">75</td></tr>\n<tr><td class="alignleft">Spanish</td><td class="alignright">70</td></tr>\n<tr><td class="alignleft">French</td><td class="alignright">48</td></tr>\n<tr><td class="alignleft">Japanese</td><td class="alignright">28</td></tr>\n<tr><td class="alignleft">Chinese</td><td class="alignright">17</td></tr>\n<tr><td class="alignleft">Italian</td><td class="alignright">13</td></tr>\n<tr><td class="alignleft">Korean</td><td class="alignright">10</td></tr>\n<tr><td class="alignleft">Dutch</td><td class="alignright">9</td></tr>\n<tr><td class="alignleft">Russian</td><td class="alignright">9</td></tr>'
var table_overall_s_m = '<tr><td class="alignleft">English</td><td class="alignright">216</td></tr>\n<tr><td class="alignleft">German</td><td class="alignright">195</td></tr>\n<tr><td class="alignleft">Chinese</td><td class="alignright">133</td></tr>\n<tr><td class="alignleft">Spanish</td><td class="alignright">108</td></tr>\n<tr><td class="alignleft">French</td><td class="alignright">48</td></tr>\n<tr><td class="alignleft">Arabic</td><td class="alignright">33</td></tr>\n<tr><td class="alignleft">Portuguese</td><td class="alignright">21</td></tr>\n<tr><td class="alignleft">Russian</td><td class="alignright">18</td></tr>\n<tr><td class="alignleft">Italian</td><td class="alignright">17</td></tr>\n<tr><td class="alignleft">Persian</td><td class="alignright">12</td></tr>'
var table_overall_d_f = '<tr><td class="alignleft">German</td><td class="alignright">215</td></tr>\n<tr><td class="alignleft">English</td><td class="alignright">67</td></tr>\n<tr><td class="alignleft">French</td><td class="alignright">35</td></tr>\n<tr><td class="alignleft">Spanish</td><td class="alignright">34</td></tr>\n<tr><td class="alignleft">Japanese</td><td class="alignright">14</td></tr>\n<tr><td class="alignleft">Korean</td><td class="alignright">10</td></tr>\n<tr><td class="alignleft">Swedish</td><td class="alignright">7</td></tr>\n<tr><td class="alignleft">Chinese</td><td class="alignright">5</td></tr>\n<tr><td class="alignleft">Vietnamese</td><td class="alignright">4</td></tr>\n<tr><td class="alignleft">Portuguese</td><td class="alignright">3</td></tr>'
var table_overall_s_f = '<tr><td class="alignleft">German</td><td class="alignright">131</td></tr>\n<tr><td class="alignleft">English</td><td class="alignright">109</td></tr>\n<tr><td class="alignleft">Chinese</td><td class="alignright">93</td></tr>\n<tr><td class="alignleft">Spanish</td><td class="alignright">55</td></tr>\n<tr><td class="alignleft">Italian</td><td class="alignright">21</td></tr>\n<tr><td class="alignleft">French</td><td class="alignright">20</td></tr>\n<tr><td class="alignleft">Korean</td><td class="alignright">14</td></tr>\n<tr><td class="alignleft">Japanese</td><td class="alignright">12</td></tr>\n<tr><td class="alignleft">Russian</td><td class="alignright">10</td></tr>\n<tr><td class="alignleft">Turkish</td><td class="alignright">9</td></tr>'
var infogain_search_1lang = { languages : ["Vietnamese"], from : "0.958", to : "0.952", gain : "0.006" }
var infogain_offer_1lang = { languages : ["Arabic"], from : "0.958", to : "0.949", gain : "0.009" }
var infogain_search = "0.931"
var infogain_offer  = "0.901"
var infogain_both   = "0.803"
var pval_mf_search = "0.00648015"
var pval_mf_offer  = "0.00000600"
var sup_vs_dem_m_tablecontent = '<table border="1" class="dataframe">\n  <thead>\n    <tr style="text-align: right;">\n      <th>#s</th>\n      <th>1</th>\n      <th>2</th>\n      <th>3</th>\n      <th>4</th>\n      <th>All</th>\n    </tr>\n    <tr>\n      <th>#o</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>1</th>\n      <td>341</td>\n      <td>30</td>\n      <td>5</td>\n      <td>1</td>\n      <td>377</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>161</td>\n      <td>23</td>\n      <td>8</td>\n      <td>1</td>\n      <td>193</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>25</td>\n      <td>6</td>\n      <td>0</td>\n      <td>0</td>\n      <td>31</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>5</td>\n      <td>1</td>\n      <td>0</td>\n      <td>0</td>\n      <td>6</td>\n    </tr>\n    <tr>\n      <th>All</th>\n      <td>532</td>\n      <td>60</td>\n      <td>13</td>\n      <td>2</td>\n      <td>607</td>\n    </tr>\n  </tbody>\n</table>'
var sup_vs_dem_m = { want_more : "7.41", same : "59.97", offer_more : "32.62" }
var sup_vs_dem_m_mean = { expected_demand : "1.15", expected_supply : "1.45"}
var sup_vs_dem_f_tablecontent = '<table border="1" class="dataframe">\n  <thead>\n    <tr style="text-align: right;">\n      <th>#s</th>\n      <th>1</th>\n      <th>2</th>\n      <th>3</th>\n      <th>4</th>\n      <th>All</th>\n    </tr>\n    <tr>\n      <th>#o</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>1</th>\n      <td>217</td>\n      <td>23</td>\n      <td>3</td>\n      <td>0</td>\n      <td>243</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>96</td>\n      <td>16</td>\n      <td>1</td>\n      <td>0</td>\n      <td>113</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>11</td>\n      <td>5</td>\n      <td>0</td>\n      <td>0</td>\n      <td>16</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>0</td>\n      <td>0</td>\n      <td>0</td>\n      <td>0</td>\n      <td>0</td>\n    </tr>\n    <tr>\n      <th>All</th>\n      <td>324</td>\n      <td>44</td>\n      <td>4</td>\n      <td>0</td>\n      <td>372</td>\n    </tr>\n  </tbody>\n</table>'
var sup_vs_dem_f = { want_more : "7.26", same : "62.63", offer_more : "30.11" }
var sup_vs_dem_f_mean = { expected_demand : "1.14", expected_supply : "1.39"}
