entries_men   = 537
entries_women = 338
entries_other = 21
var weekday_distribution_m = [18.25, 14.90, 17.32, 16.01, 12.66, 9.12, 11.73]
var weekday_distribution_f = [15.09, 17.16, 17.46, 13.31, 15.09, 10.65, 11.24]
var weekday_chi = "0.630599173"
var table_overall_d_m = '<tr><td class="alignleft">German</td><td class="alignright">331</td></tr>\n<tr><td class="alignleft">English</td><td class="alignright">69</td></tr>\n<tr><td class="alignleft">Spanish</td><td class="alignright">65</td></tr>\n<tr><td class="alignleft">French</td><td class="alignright">44</td></tr>\n<tr><td class="alignleft">Japanese</td><td class="alignright">25</td></tr>\n<tr><td class="alignleft">Chinese</td><td class="alignright">14</td></tr>\n<tr><td class="alignleft">Italian</td><td class="alignright">12</td></tr>\n<tr><td class="alignleft">Dutch</td><td class="alignright">9</td></tr>\n<tr><td class="alignleft">Russian</td><td class="alignright">8</td></tr>\n<tr><td class="alignleft">Korean</td><td class="alignright">7</td></tr>'
var table_overall_s_m = '<tr><td class="alignleft">English</td><td class="alignright">187</td></tr>\n<tr><td class="alignleft">German</td><td class="alignright">176</td></tr>\n<tr><td class="alignleft">Chinese</td><td class="alignright">120</td></tr>\n<tr><td class="alignleft">Spanish</td><td class="alignright">94</td></tr>\n<tr><td class="alignleft">French</td><td class="alignright">42</td></tr>\n<tr><td class="alignleft">Arabic</td><td class="alignright">31</td></tr>\n<tr><td class="alignleft">Portuguese</td><td class="alignright">18</td></tr>\n<tr><td class="alignleft">Russian</td><td class="alignright">14</td></tr>\n<tr><td class="alignleft">Italian</td><td class="alignright">14</td></tr>\n<tr><td class="alignleft">Turkish</td><td class="alignright">11</td></tr>'
var table_overall_d_f = '<tr><td class="alignleft">German</td><td class="alignright">195</td></tr>\n<tr><td class="alignleft">English</td><td class="alignright">60</td></tr>\n<tr><td class="alignleft">French</td><td class="alignright">34</td></tr>\n<tr><td class="alignleft">Spanish</td><td class="alignright">32</td></tr>\n<tr><td class="alignleft">Japanese</td><td class="alignright">13</td></tr>\n<tr><td class="alignleft">Korean</td><td class="alignright">7</td></tr>\n<tr><td class="alignleft">Swedish</td><td class="alignright">5</td></tr>\n<tr><td class="alignleft">Vietnamese</td><td class="alignright">4</td></tr>\n<tr><td class="alignleft">Portuguese</td><td class="alignright">3</td></tr>\n<tr><td class="alignleft">Chinese</td><td class="alignright">3</td></tr>'
var table_overall_s_f = '<tr><td class="alignleft">German</td><td class="alignright">118</td></tr>\n<tr><td class="alignleft">English</td><td class="alignright">96</td></tr>\n<tr><td class="alignleft">Chinese</td><td class="alignright">82</td></tr>\n<tr><td class="alignleft">Spanish</td><td class="alignright">52</td></tr>\n<tr><td class="alignleft">Italian</td><td class="alignright">21</td></tr>\n<tr><td class="alignleft">French</td><td class="alignright">19</td></tr>\n<tr><td class="alignleft">Korean</td><td class="alignright">12</td></tr>\n<tr><td class="alignleft">Japanese</td><td class="alignright">11</td></tr>\n<tr><td class="alignleft">Russian</td><td class="alignright">9</td></tr>\n<tr><td class="alignleft">Turkish</td><td class="alignright">8</td></tr>'
var infogain_search = { languages : ["English"], from : "0.957", to : "0.952", gain : "0.004" }
var infogain_offer = { languages : ["Arabic"], from : "0.962", to : "0.953", gain : "0.009" }
var pval_mf_search = "0.03807909"
var pval_mf_offer  = "0.00001165"
